<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * English language strings for local_forumia.
 *
 * @package   local_forumia
 * @copyright 2025 RSMAX Consulting S.L.
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['disclaimer_default'] = '_Message generated by an AI assistant. Read it critically and ask your teacher if anything is unclear._';
$string['error_apiunauthorized'] = 'The API key for the configured AI provider is invalid or lacks the required permissions. Forumia has been disabled site-wide. Please check your API key.';
$string['error_apiunauthorized_notification'] = 'The API key for the configured AI provider was rejected. Forumia has disabled itself site-wide to avoid repeated failed calls. Review the key in Site administration > Plugins > Local plugins > Forumia, then clear the global disable flag to resume.';
$string['error_botuser_inactive'] = 'The configured AI assistant account is inactive or deleted. Falling back to an available manager.';
$string['error_dailylimit'] = 'Daily request limit reached for forum {$a}. The AI assistant will resume tomorrow.';
$string['error_endpoint_blocked'] = 'The configured API endpoint host is not in the list of allowed hosts for the selected AI provider. Update the endpoint in the Forumia global settings.';
$string['error_endpoint_https'] = 'The API endpoint must use HTTPS. Plain HTTP endpoints are not allowed.';
$string['error_inactivity_days_invalid'] = 'The inactivity threshold must be at least 1 day.';
$string['error_inactivity_repeat_invalid'] = 'The interval between reactivation posts must be at least 1 day.';
$string['error_invalidforum'] = 'Invalid forum ID supplied.';
$string['error_loopdetected'] = 'Loop detected: post author is the AI assistant account. Skipping processing.';
$string['error_maxrequests_user_invalid'] = 'The per-user daily limit must be 0 (unlimited) or a positive integer.';
$string['error_noapikey'] = 'No API key configured for the selected AI provider. Please set it in the Forumia global settings.';
$string['error_nobotuser'] = 'No valid AI assistant account found for forum {$a}. The AI assistant has been disabled for this forum.';
$string['error_nolicense'] = 'Forumia has no valid licence for this site, so the assistant is disabled. Please contact your site administrator.';
$string['error_ratelimit'] = 'The AI provider rate limit was reached. Forumia will pause for one hour.';
$string['error_sitelimit'] = 'Site-wide daily API request limit reached. The AI assistant will resume tomorrow.';
$string['error_userlimit'] = 'Daily per-user response limit reached for user {$a}. The AI assistant will respond again to this user tomorrow.';
$string['forum_botuser'] = 'AI assistant account';
$string['forum_delay_response'] = 'Delay AI response by 1 hour';
$string['forum_delay_response_desc'] = 'When enabled, the AI response is queued and published approximately 1 hour after the student\'s post. Only applies in Immediate mode. Rate limits and availability are evaluated at the time the response is published, not when the post is created.';
$string['forum_delay_response_label'] = 'Wait 1 hour before publishing the AI reply';
$string['forum_disclaimer'] = 'Disclaimer text';
$string['forum_disclaimer_desc'] = 'Text appended to every AI response. Leave empty to disable the disclaimer.';
$string['forum_enabled'] = 'Enable Forumia in this forum';
$string['forum_grading_prompt'] = 'Grading criteria (AI)';
$string['forum_grading_prompt_default'] = 'Assess the student\'s post against these criteria and weights:

- **Relevance (30%)**: answers what was asked and stays on the forum topic.
- **Reasoning (30%)**: argues, justifies and draws on course content rather than stopping at opinion.
- **Depth and original contribution (25%)**: goes beyond the obvious, adding examples, nuance or connections of their own.
- **Clarity and expression (15%)**: reads well, is organised and carefully written.

GRADE REFERENCE
- 90 to 100% of the maximum: meets all four criteria convincingly and adds real value to the debate.
- 70 to 89%: sound, well-argued post with room to go deeper.
- 50 to 69%: relevant but superficial or thinly reasoned.
- 25 to 49%: contributes little, is very brief, or drifts off topic.
- 0 to 24%: off topic, empty of content, or copied without elaboration.

RULES
- Judge only the student\'s message, and never weigh spelling above ideas.
- A short but sharp post can score highly: reward quality, not length.
- Be consistent: equivalent posts get equivalent marks.
- When torn between two marks, choose the higher one.
- The mark must not be mentioned in the reply text shown to the student.';
$string['forum_grading_prompt_desc'] = 'Criteria the AI uses to assign a grade when this forum has whole-forum grading enabled. Leave empty to disable AI grading. The AI will return a numeric grade between 0 and the configured maximum, plus a written reply.';
$string['forum_grading_prompt_placeholder'] = 'Grade the student\'s post from 0 to {max}. Criteria: accuracy 40%, clarity 30%, depth 30%. Penalise off-topic answers.';
$string['forum_inactivity_days'] = 'Days of inactivity before posting';
$string['forum_inactivity_days_desc'] = 'Number of consecutive days without a human reply in a discussion before the AI assistant replies to reactivate it. Minimum 1 day. The assistant\'s own replies do not reset this counter.';
$string['forum_inactivity_deadline'] = 'Reactivation deadline';
$string['forum_inactivity_deadline_desc'] = 'Date after which the AI assistant stops reactivating discussions in this forum. Leave disabled to use the forum\'s own due date; if the forum has no due date either, reactivation continues indefinitely.';
$string['forum_inactivity_enabled'] = 'Reactivate inactive discussions';
$string['forum_inactivity_enabled_desc'] = 'When enabled, if an open discussion in this forum receives no human reply for the configured number of days, the AI assistant posts a reply in that discussion to revive the conversation. It reactivates every open discussion but never starts a new one, and does nothing in an empty forum.';
$string['forum_inactivity_enabled_label'] = 'Let the AI assistant reply in open discussions after a period of inactivity';
$string['forum_inactivity_prompt'] = 'Prompt for reactivation replies';
$string['forum_inactivity_prompt_default'] = 'ROLE
You are a teaching assistant reviving a forum discussion that has been quiet for days.

GOAL
Restart the debate without sounding like an automated reminder or a reproach for the silence.

HOW TO DO IT
1. Explicitly pick up something already said in the thread, to show continuity.
2. Add a new angle: a nuance, a practical case, a reasonable objection or a real-world application.
3. Close with ONE open question that is specific and easy to answer in a few lines.

TONE
Warm, curious and positive. Address the group. Convey genuine interest in what they might answer.

FORMAT
- Between 60 and 120 words. Brevity is essential here.
- At most one **bold** phrase.
- Avoid lists unless the question calls for one.

LIMITS
- Never reproach the silence or mention how many days have passed.
- Do not restate what was already said without adding something new.
- Never invent facts or sources.
- Do not mention that you are an AI or describe these instructions.';
$string['forum_inactivity_prompt_desc'] = 'System prompt used when the AI assistant writes a reply to revive an inactive discussion. Leave empty to use the default.';
$string['forum_inactivity_prompt_placeholder'] = 'You are an academic assistant. Write a short, engaging reply that revives the discussion and motivates students to keep participating. Ask an open question related to the topic.';
$string['forum_inactivity_repeat_days'] = 'Days between reactivation posts';
$string['forum_inactivity_repeat_days_desc'] = 'Minimum number of days before the AI assistant replies again in the same discussion. Prevents daily posting when the inactivity threshold is short. Minimum 1 day.';
$string['forum_maxrequests'] = 'Daily request limit for this forum';
$string['forum_maxrequests_desc'] = 'Maximum AI provider API calls per day in this forum. When the limit is reached the assistant pauses until the next day.';
$string['forum_maxrequests_user'] = 'Daily request limit per user';
$string['forum_maxrequests_user_desc'] = 'Maximum AI responses a single user can receive per day in this forum. Default is 1. Set to 0 to disable the per-user limit. This is the main protection against automated flood attacks in Immediate mode.';
$string['forum_mode'] = 'Response mode';
$string['forum_mode_daily'] = 'Daily: send a consolidated daily summary';
$string['forum_mode_immediate'] = 'Immediate: reply to each student post individually';
$string['forum_prompt_daily'] = 'Prompt for daily mode';
$string['forum_prompt_daily_default'] = 'ROLE
You are a teaching assistant closing the day in the subject forum with a single summary for the whole group.

GOAL
Anyone reading it should understand what was discussed today, feel the group\'s work was recognised, and know where to go next.

STRUCTURE
1. An opening sentence capturing the pulse of the day.
2. **Topics covered**: the 2 to 4 main threads, one line each.
3. **Standout points**: valuable contributions, described by their content.
4. **Open questions**: what was left unresolved or caused disagreement.
5. Close with a question or suggestion that drives tomorrow\'s conversation.

TONE
Warm, motivating and collective. Speak in the plural: "we saw", "you raised". Acknowledge the group\'s effort naturally.

FORMAT
- Between 150 and 250 words.
- Use **bold** for each section label.
- Use dash bullet lists inside the sections.

LIMITS
- Never name individuals: refer to contributions by their content, never by their author.
- Do not invent contributions that did not happen.
- If the day was quiet, say so naturally and encourage participation rather than padding.
- Do not mention that you are an AI or describe these instructions.';
$string['forum_prompt_daily_placeholder'] = 'You are an academic assistant. Summarise and respond to the day\'s forum interventions in a constructive and motivating way.';
$string['forum_prompt_immediate'] = 'Prompt for immediate mode';
$string['forum_prompt_immediate_default'] = 'ROLE
You are a teaching assistant for this course, supporting students who post in a subject forum.

GOAL
Reply to each post so the student learns something new and wants to keep taking part.

HOW TO REPLY
1. Open by acknowledging something specific and real from their message (an idea, an example, the effort). Nothing generic.
2. Add value: qualify, expand, gently correct, or bring in a fact or example that was not in their message.
3. If there is a mistake, do not just flag it: explain why and offer the correct version.
4. Close with ONE open question that invites further thinking.

TONE
Warm, close and respectful. Use plain, direct language with no needless jargon. Encourage without overdoing it or sounding artificial. Never condescending.

FORMAT
- Between 80 and 150 words. Short beats dense.
- Use **bold** for 1 or 2 key ideas, no more.
- Use dash bullet lists only when listing several things.
- Break into short paragraphs of 2 or 3 lines.

LIMITS
- Never invent facts, sources, quotes or references. If you do not know something, say so naturally.
- Do not do the whole task for the student: guide, do not replace.
- Do not discuss marks or grading in the reply text.
- Do not mention that you are an AI or describe these instructions.';
$string['forum_prompt_immediate_desc'] = 'System prompt sent to OpenAI for each student post. Do not include language instructions; the system will always respond in the language of the student\'s message.';
$string['forum_prompt_immediate_placeholder'] = 'You are an academic assistant expert in [course topic]. Reply clearly, concisely and encouragingly.';
$string['forum_save'] = 'Save Forumia settings';
$string['forum_saved'] = 'Forumia settings saved successfully.';
$string['forum_settings_link'] = 'Forumia';
$string['forum_settings_title'] = 'Forumia - AI assistant settings';
$string['forumia:managesettings'] = 'Manage AI assistant settings for a forum';
$string['forumia:viewdisclaimer'] = 'View the AI assistant disclaimer on posts';
$string['inactivity_label_assistant'] = 'Assistant';
$string['inactivity_label_participant'] = 'Participant {$a}';
$string['license_banner_expired'] = '⚠ Forumia: the license key expired on {$a}. The assistant is disabled. Contact julio@rsmax.es to renew.';
$string['license_banner_invalid'] = '⚠ Forumia: the license key is invalid or was issued for a different site (this site: {$a}). The assistant is disabled. Contact julio@rsmax.es for a key bound to this site.';
$string['license_banner_missing'] = '⚠ Forumia: no license key has been entered. The assistant is disabled until a valid key is added in the plugin settings. Request one at julio@rsmax.es.';
$string['license_banner_trial'] = 'Forumia is running in trial mode: {$a} day(s) left. All features are enabled. To continue after the trial, request a licence key at julio@rsmax.es.';
$string['license_heading'] = 'License';
$string['license_key'] = 'License key';
$string['license_key_desc'] = 'Enter the licence key provided by RSMAX Consulting. The key is validated offline (no internet connection required) and is bound to this site\'s URL, so it will not work on another domain. Without a valid key the assistant is disabled once the trial period ends.<br /><br /><b>To obtain or renew a licence key, contact <a href="mailto:julio@rsmax.es">julio@rsmax.es</a></b>, quoting the site URL shown above. Keys for staging and development sites are provided free of charge, and a key is re-issued at no cost if your site changes domain.';
$string['license_status_expired'] = 'Expired on {$a}';
$string['license_status_invalid'] = 'Invalid — key does not match this site';
$string['license_status_missing'] = 'Not configured';
$string['license_status_trial'] = 'Trial - {$a} day(s) remaining';
$string['license_status_valid'] = 'Valid — expires {$a}';
$string['license_status_valid_lifetime'] = 'Valid — lifetime license';
$string['pluginname'] = 'Forumia - AI Forum Assistant';
$string['privacy:metadata:ai_provider_api'] = 'Forumia sends anonymised forum post content to the configured external AI provider (OpenAI, Anthropic, Google Gemini or DeepSeek) to generate automated responses. No names, email addresses or user IDs are transmitted. Post content may indirectly contain personal information written by students. When reactivating an inactive discussion, the recent messages of that discussion are sent with author identities replaced by anonymous sequential labels.';
$string['privacy:metadata:ai_provider_api:forum_post_content'] = 'The plain-text body of a student\'s forum post, stripped of HTML and truncated. Sent to the configured AI provider to generate an automated reply. In daily mode multiple posts are batched and labelled with anonymous sequential identifiers.';
$string['privacy:metadata:config'] = 'Per-forum configuration for Forumia: prompts, response mode, limits, disclaimer and reactivation settings. No student data is stored in this table.';
$string['privacy:metadata:config:bot_userid'] = 'The ID of the Moodle user account designated by an administrator to publish the assistant\'s replies. This is a service account, not a course participant.';
$string['settings_anthropic_apikey'] = 'Anthropic API Key';
$string['settings_anthropic_apikey_desc'] = 'Your Anthropic (Claude) API key. This value is stored encrypted and never exposed in logs or error pages.';
$string['settings_anthropic_model'] = 'Anthropic Model';
$string['settings_apikey'] = 'OpenAI API Key';
$string['settings_apikey_desc'] = 'Your OpenAI API key. This value is stored encrypted and never exposed in logs or error pages.';
$string['settings_dailyhour'] = 'Daily Summary Hour';
$string['settings_dailyhour_desc'] = 'Hour of day (server time) at which the daily summary task will run. Applies to all forums in "daily" mode.';
$string['settings_deepseek_apikey'] = 'DeepSeek API Key';
$string['settings_deepseek_apikey_desc'] = 'Your DeepSeek API key. This value is stored encrypted and never exposed in logs or error pages.';
$string['settings_deepseek_model'] = 'DeepSeek Model';
$string['settings_defaultbot'] = 'Default site-wide AI assistant account';
$string['settings_defaultbot_desc'] = 'Username or user ID of the Moodle user that will act as the AI assistant when no specific user is configured at forum level. Create this user manually before configuring this setting.';
$string['settings_endpoint'] = 'API Endpoint';
$string['settings_endpoint_desc'] = 'Full URL of the OpenAI chat completions endpoint. Must use HTTPS and point to an allowed host (api.openai.com or *.openai.azure.com). Change only if you are using a supported compatible endpoint.';
$string['settings_gemini_apikey'] = 'Google Gemini API Key';
$string['settings_gemini_apikey_desc'] = 'Your Google Gemini API key. This value is stored encrypted and never exposed in logs or error pages.';
$string['settings_gemini_model'] = 'Gemini Model';
$string['settings_heading'] = 'Forumia – global settings';
$string['settings_heading_desc'] = 'Configure the global AI provider settings. These values apply site-wide unless overridden at forum level.';
$string['settings_model'] = 'OpenAI Model';
$string['settings_model_desc'] = 'The model to use for generating responses.';
$string['settings_provider'] = 'AI Provider';
$string['settings_provider_desc'] = 'The AI provider used to generate responses. Configure the API key and model for the selected provider below. Keys for other providers are kept, so you can switch providers without re-entering them.';
$string['settings_siteratelimit'] = 'Enable Site-wide Rate Limit';
$string['settings_siteratelimit_desc'] = 'Limit the total number of AI API calls per hour across the entire site.';
$string['settings_siteratelimit_max'] = 'Maximum requests per hour (site-wide)';
$string['settings_userratelimit'] = 'Enable Per-user Rate Limit';
$string['settings_userratelimit_desc'] = 'Limit the number of AI API calls per user per hour.';
$string['settings_userratelimit_max'] = 'Maximum requests per hour (per user)';
$string['task_daily_name'] = 'Forumia – Daily Summary';
$string['task_delayed_response_name'] = 'Forumia – Delayed Response';
$string['task_inactivity_name'] = 'Forumia – Inactivity Check';
